#!/bin/bash

NOMAD_DOCKER_COMMAND=$*

if [ -z "$NOMAD_DOCKER_CONTAINER_NAME" ]; then
  echo 'Please set $NOMAD_DOCKER_CONTAINER_NAME'
  exit
fi

if [ -z "$NOMAD_DOCKER_COMMAND" ]; then
  echo 'Please set $NOMAD_DOCKER_COMMAND'
  exit
fi

if ! [ -z "$NOMAD_DOCKER_REGISTRY_URL" ]; then
  echo "Logging in to $NOMAD_DOCKER_REGISTRY_URL"
  docker login -u $NOMAD_DOCKER_REGISTRY_USER \
    -p $NOMAD_DOCKER_REGISTRY_PASSWORD \
    -e $NOMAD_DOCKER_REGISTRY_EMAIL \
    $NOMAD_DOCKER_REGISTRY_URL
fi

echo "Stopping container $NOMAD_DOCKER_CONTAINER_NAME"
docker stop $NOMAD_DOCKER_CONTAINER_NAME

echo "Removing container $NOMAD_DOCKER_CONTAINER_NAME"
docker rm $NOMAD_DOCKER_CONTAINER_NAME

if ! [ -z "$NOMAD_DOCKER_PULL_COMMAND" ]; then
  echo "Executing docker pull $NOMAD_DOCKER_PULL_COMMAND"
  docker pull $NOMAD_DOCKER_PULL_COMMAND
fi

if ! [ -z "$NOMAD_DOCKER_ENVSUBST" ]; then
  echo "Replacing environment variables in $NOMAD_DOCKER_COMMAND"
  NOMAD_DOCKER_COMMAND=$(echo $NOMAD_DOCKER_COMMAND | envsubst)
fi

_stop() {
  echo "Stopping container $NOMAD_DOCKER_CONTAINER_NAME"
  docker stop $NOMAD_DOCKER_CONTAINER_NAME
}

echo "Trapping SIGINT, SIGTERM and SIGKILL"
trap _stop SIGINT
trap _stop SIGTERM
trap _stop SIGKILL

echo "Starting container $NOMAD_DOCKER_CONTAINER_NAME"
docker run -d \
  --name $NOMAD_DOCKER_CONTAINER_NAME \
  $NOMAD_DOCKER_COMMAND

echo "Waiting for container $NOMAD_DOCKER_CONTAINER_NAME to finish"
docker wait $NOMAD_DOCKER_CONTAINER_NAME &
wait $!
